--Statistics gathering for Database, schema and table.
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME => 'SCHEMA NAME',CASCADE => TRUE,  DEGREE => 6   ); 
EXECUTE DBMS_STATS.GATHER_DATABASE_STATS(OWNNAME => 'SCHEMA NAME',CASCADE => TRUE,  DEGREE => 6   ); 
EXECUTE DBMS_STATS.GATHER_TABLE_STATS(OWNNAME => 'SCHEMA NAME',CASCADE => TRUE,  DEGREE => 6   ); 


--Delete the existing Statistics and Histograms
EXECUTE DBMS_STATS.DELETE_SCHEMA_STATS('SCHEMA_NAME');

--Gather the schema stats without Histograms
EXEC DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME=>'SCHEMA_NAME', ESTIMATE_PERCENT=> 100, METHOD_OPT=>'for all columns size 1', DEGREE =>6, CASCADE =>TRUE);