/* Formatted on 10/27/2023 5:37:58 PM (QP5 v5.381) */
CREATE USER OFSDEFQ IDENTIFIED BY OFSDEFQ
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    PROFILE DEFAULT
    ACCOUNT UNLOCK;

GRANT OLAP_USER TO OFSDEFQ;

ALTER USER OFSDEFQ
    DEFAULT ROLE ALL;

GRANT CREATE MATERIALIZED VIEW TO OFSDEFQ;
GRANT CREATE PROCEDURE TO OFSDEFQ;
GRANT CREATE SEQUENCE TO OFSDEFQ;
GRANT CREATE SESSION TO OFSDEFQ;
GRANT CREATE SYNONYM TO OFSDEFQ;
GRANT CREATE TABLE TO OFSDEFQ;
GRANT CREATE TRIGGER TO OFSDEFQ;
GRANT CREATE TYPE TO OFSDEFQ;
GRANT CREATE VIEW TO OFSDEFQ;
GRANT DROP ANY INDEX TO OFSDEFQ;

ALTER USER OFSDEFQ
    QUOTA UNLIMITED ON USERS;

GRANT SELECT ON SYS.V_$PARAMETER TO OFSDEFQ;